# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title                  : VeloxChem program manual
author                 : The VeloxChem team
logo                   : images/logo/vlx-logo-blacktext-halo.png
copyright              : "2025"
exclude_patterns       : [ README.md ]
only_build_toc_files   : false

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache
  timeout: 120

#Sphinx settings
#Force a more recent version of the math engine mathjax
sphinx:
  config:
    suppress_warnings: ["mystnb.unknown_mime_type"]
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    myst_heading_anchors: 3

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - dollarmath

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/kthpanor/vlxman
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master      # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  favicon: vlx_logo_mark.png
  home_page_in_navbar: false